In [3]:
import numpy as np
from numpy.random import randn
from numpy.linalg import *

In [4]:
#정사각 행렬의 대각 원소 값을 지정하고, 나머지는 0으로 채움
print(np.diag((1,2,3,4)))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [5]:
#행렬 곱셈
arr = np.array([[1,2],[3,4]])
arr2 = np.array([[2,2],[2,2]])
print(arr.dot(arr2))

[[ 6  6]
 [14 14]]


In [6]:
#대각선 원소의 합
np.trace(np.diag((1,2,3,4)))

10

In [16]:
A=np.array([[2,4,-2],[4,9,-3],[-2,-3,7]])
#행렬식 계산 determinant
d=np.linalg.det(A)
d

7.999999999999998

In [8]:
#역행렬 inverse
A1=np.linalg.inv(A)
A1

array([[ 6.75, -2.75,  0.75],
       [-2.75,  1.25, -0.25],
       [ 0.75, -0.25,  0.25]])

svd 특이값분해
m*n 행렬을 대각화하는 방법

In [9]:
#solve 가우스 소거법 : Ax=b를 만족하는 x 구하기
b=np.array([2,8,10])
x=np.linalg.solve(A,b)
x

array([-1.,  2.,  2.])

In [10]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
c = np.linalg.solve(a, b)
c

array([2., 3.])

np.linalg.lstsq(객체1(x), 객체2(y)): 최소자승법에 의한 선형 행렬방정식의 해를 계산 즉, 행렬 x,y 사이의 y=bx+e의 모형을 구축할 경우 실제 y와 추정 y 사이의 차이를 최소로 하는 조건을 만족시키는 과정을 최소자승법이라한다. 이러한 절차에 의해 선형모형의 계수행렬(b)를 계산한다. 이 함수는 계수와 잔차제곱합, rank, 특이값(singular value)을 반환한다.

In [11]:
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])
x = np.vstack([x, np.ones(len(x))]).T
x

array([[0., 1.],
       [1., 1.],
       [2., 1.],
       [3., 1.]])

In [12]:
m, c = np.linalg.lstsq(x, y)[0]
print(m, c)

0.9999999999999997 -0.9499999999999992


C:\Users\edu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [13]:
b, ssr, rank, sv=np.linalg.lstsq(x, y)
print(b)
print(ssr)
print(rank)
print(sv)

[ 1.   -0.95]
[0.05]
2
[4.10003045 1.09075677]


C:\Users\edu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.
